require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.dashboard"
require "user.nvim-tree"
require "user.autopairs"
require "user.gitsigns"
require "user.bufferline"
require "user.lualine"
require "user.telescope"
require "user.cmp"
require "user.lsp"
require "user.treesitter" --install llvm
